name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '12'

      - name: Install dependencies
        run: npm install

#      - name: Build
#        run: npm run build

      - name: Deploy to Server
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/cicd
            npm install
            cd
            pm2 ls
            pm2 restart dev
