name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7


        with:
          host: ${{ secrets.INPUT_HOST }}
          username: ${{ secrets.INPUT_USERNAME }}
          key: ${{ secrets.INPUT_KEY }}
          script: |
            cd /var/www/cicd
            npm install
            cd
            pm2 ls
            pm2 restart dev
